name: 'PHPStan Baseline Warnings'
description: 'Generate GitHub-compatible warning annotations from PHPStan baseline files'
author: 'juampi92'

inputs:
  baseline-path:
    description: 'Path to the PHPStan baseline file'
    required: true
    default: 'phpstan-baseline.neon'
  base-dir:
    description: 'Base directory for PHPStan'
    required: true
    default: './'

runs:
  using: 'composite'
  steps:
    - name: Configure git
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        coverage: none

    - name: Get changed PHP files
      id: changed-files
      uses: tj-actions/changed-files@v40
      with:
        files: |
          **/*.php

    - name: Create isolated environment
      shell: bash
      run: |
        # Create a temporary directory for our action
        mkdir -p /tmp/phpstan-warnings-action
        cd /tmp/phpstan-warnings-action
        
        # Initialize a new composer project
        composer init --name=action/phpstan-warnings --type=project --no-interaction
        
        # Add our package as the only requirement
        composer require juampi92/phpstan-baseline-warnings

    - name: Run PHPStan Baseline Warnings
      shell: bash
      run: |
        /tmp/phpstan-warnings-action/vendor/bin/phpstan-baseline-warnings \
          --baseline-path="${{ inputs.baseline-path }}" \
          --base-dir="${{ inputs.base-dir }}" \
          ${{ steps.changed-files.outputs.all_changed_files }}

branding:
  icon: 'alert-triangle'
  color: 'yellow'
