name: 'PHPStan Baseline Warnings'
description: 'Generate GitHub-compatible warning annotations from PHPStan baseline files'
author: 'juampi92'

inputs:
  baseline-path:
    description: 'Path to the PHPStan baseline file'
    required: true
    default: 'phpstan-baseline.neon'
  base-dir:
    description: 'Base directory for PHPStan'
    required: true
    default: './'

runs:
  using: 'composite'
  steps:
    - name: Configure git
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Get changed PHP files
      id: changed-files
      uses: tj-actions/changed-files@v40
      with:
        files: |
          **/*.php

    - name: Set files env
      shell: bash
      run: |
        echo "files=${{ steps.changed-files.outputs.all_changed_files }}" >> $GITHUB_ENV

    - name: Run PHPStan Baseline Warnings
      shell: bash
      run: phpstan-baseline-warnings --baseline-path="${{ inputs.baseline-path }}" --base-dir="${{ inputs.base-dir }}" $files

branding:
  icon: 'alert-triangle'
  color: 'yellow'
